const primary = [
    {id: 1, parent: null, hex: '#FFC0CB'},
    {id: 2, parent: null, hex: '#FF69B4'},
    {id: 3, parent: null, hex: '#FF1493'},
    {id: 4, parent: null, hex: '#DB7093'},
    {id: 5, parent: null, hex: '#C71585'},
    {id: 6, parent: null, hex: '#E6E6FA'},
    {id: 7, parent: null, hex: '#D8BFD8'},
    {id: 8, parent: null, hex: '#DDA0DD'},
    {id: 9, parent: null, hex: '#DA70D6'},
    {id: 10, parent: null, hex: '#BA55D3'},
    {id: 11, parent: null, hex: '#9932CC'},
    {id: 12, parent: null, hex: '#8B008B'},
    
    {id: 13, parent: null, hex: '#FFA07A'},
    {id: 14, parent: null, hex: '#FF69B4'},
    {id: 15, parent: null, hex: '#FF1493'},
    {id: 16, parent: null, hex: '#DB7093'},
    {id: 17, parent: null, hex: '#C71585'},
    {id: 18, parent: null, hex: '#E6E6FA'},
    {id: 19, parent: null, hex: '#D8BFD8'},
    {id: 20, parent: null, hex: '#DDA0DD'},
    {id: 21, parent: null, hex: '#DA70D6'},
    {id: 22, parent: null, hex: '#BA55D3'},
    {id: 23, parent: null, hex: '#9932CC'},
    {id: 24, parent: null, hex: '#8B008B'},

    {id: 25, parent: null, hex: '#FFC0CB'},
    {id: 26, parent: null, hex: '#FF69B4'},
    {id: 27, parent: null, hex: '#FF1493'},
    {id: 28, parent: null, hex: '#DB7093'},
    {id: 29, parent: null, hex: '#C71585'},
    {id: 30, parent: null, hex: '#E6E6FA'},
    {id: 31, parent: null, hex: '#D8BFD8'},
    {id: 32, parent: null, hex: '#DDA0DD'},
    {id: 33, parent: null, hex: '#DA70D6'},
    {id: 34, parent: null, hex: '#BA55D3'},
    {id: 35, parent: null, hex: '#9932CC'},
    {id: 36, parent: null, hex: '#8B008B'},

    {id: 37, parent: null, hex: '#FFC0CB'},
    {id: 38, parent: null, hex: '#FF69B4'},
    {id: 39, parent: null, hex: '#FF1493'},
    {id: 40, parent: null, hex: '#DB7093'},
    {id: 41, parent: null, hex: '#C71585'},
    {id: 42, parent: null, hex: '#E6E6FA'},
    {id: 43, parent: null, hex: '#D8BFD8'},
    {id: 44, parent: null, hex: '#DDA0DD'},
    {id: 45, parent: null, hex: '#DA70D6'},
    {id: 46, parent: null, hex: '#BA55D3'},
    {id: 47, parent: null, hex: '#9932CC'},
    {id: 48, parent: null, hex: '#8B008B'},

    {id: 49, parent: null, hex: '#FFC0CB'},
    {id: 50, parent: null, hex: '#FF69B4'},
    {id: 51, parent: null, hex: '#FF1493'},
    {id: 52, parent: null, hex: '#DB7093'},
    {id: 53, parent: null, hex: '#C71585'},
    {id: 54, parent: null, hex: '#E6E6FA'},
    {id: 55, parent: null, hex: '#D8BFD8'},
    {id: 56, parent: null, hex: '#DDA0DD'},
    {id: 57, parent: null, hex: '#DA70D6'},
    {id: 58, parent: null, hex: '#BA55D3'},
    {id: 59, parent: null, hex: '#9932CC'},
    {id: 60, parent: null, hex: '#8B008B'},

    {id: 61, parent: null, hex: '#FFC0CB'},
    {id: 62, parent: null, hex: '#FF69B4'},
    {id: 63, parent: null, hex: '#FF1493'},
    {id: 64, parent: null, hex: '#DB7093'},
    {id: 65, parent: null, hex: '#C71585'},
    {id: 66, parent: null, hex: '#E6E6FA'},
    {id: 67, parent: null, hex: '#D8BFD8'},
    {id: 68, parent: null, hex: '#DDA0DD'},
    {id: 69, parent: null, hex: '#DA70D6'},
    {id: 70, parent: null, hex: '#BA55D3'},
    {id: 71, parent: null, hex: '#9932CC'},
    {id: 72, parent: null, hex: '#8B008B'}

    // {id: , parent: null, hex: '#FFC0CB'},
    // {id: , parent: null, hex: '#FF69B4'},
    // {id: , parent: null, hex: '#FF1493'},
    // {id: , parent: null, hex: '#DB7093'},
    // {id: , parent: null, hex: '#C71585'},
    // {id: , parent: null, hex: '#E6E6FA'},
    // {id: , parent: null, hex: '#D8BFD8'},
    // {id: , parent: null, hex: '#DDA0DD'},
    // {id: , parent: null, hex: '#DA70D6'},
    // {id: , parent: null, hex: '#BA55D3'},
    // {id: , parent: null, hex: '#9932CC'},
    // {id: , parent: null, hex: '#8B008B'},

    // {id: , parent: null, hex: '#FFC0CB'},
    // {id: , parent: null, hex: '#FF69B4'},
    // {id: , parent: null, hex: '#FF1493'},
    // {id: , parent: null, hex: '#DB7093'},
    // {id: , parent: null, hex: '#C71585'},
    // {id: , parent: null, hex: '#E6E6FA'},
    // {id: , parent: null, hex: '#D8BFD8'},
    // {id: , parent: null, hex: '#DDA0DD'},
    // {id: , parent: null, hex: '#DA70D6'},
    // {id: , parent: null, hex: '#BA55D3'},
    // {id: , parent: null, hex: '#9932CC'},
    // {id: , parent: null, hex: '#8B008B'},
]

const shades = [
    {id: 'A', parent: '#E6E6FA', hex: '#ffffff'},
    {id: 'A', parent: '#E6E6FA', hex: '#eaeafb'},
    {id: 'A', parent: '#E6E6FA', hex: '#d4d4f7'},
    {id: 'A', parent: '#E6E6FA', hex: '#bfbff2'}
]


module.exports = {
    primary,
    shades
};